spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service-public
              uri: lb://product-service
              predicates:
                - Path=/products/**,/categories/**,/brands/**,/gpus/**,/cpus/**,/motherboards/**,/pccases/**,/psus/**,/ramkits/**
              filters:
                - name: OptFilter

            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/carts/**
              filters:
                - name: JwtAuthFilter

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
              filters:
                - name: JwtAuthFilter

            - id: order-service-payment
              uri: lb://order-service
              predicates:
                - Path=/stripe/**

            - id: auth-service-auth
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
              filters:
                - name: OptFilter

            - id: auth-service-users
              uri: lb://auth-service
              predicates:
                - Path=/users/**
              filters:
                - name: JwtAuthFilter

            - id: cart-service-docs
              uri: lb://cart-service
              predicates:
                - Path=/cart-service/api-docs/**,/cart-service/swagger-ui/**
              filters:
                - RewritePath=/cart-service/api-docs(?<segment>.*), /api-docs$\{segment}
                - RewritePath=/cart-service/swagger-ui(?<segment>.*), /swagger-ui$\{segment}

            - id: auth-service-docs
              uri: lb://auth-service
              predicates:
                - Path=/auth-service/api-docs/**,/auth-service/swagger-ui/**
              filters:
                - RewritePath=/auth-service/api-docs(?<segment>.*), /api-docs$\{segment}
                - RewritePath=/auth-service/swagger-ui(?<segment>.*), /swagger-ui$\{segment}

            - id: order-service-docs
              uri: lb://order-service
              predicates:
                - Path=/order-service/api-docs/**,/order-service/swagger-ui/**
              filters:
                - RewritePath=/order-service/api-docs(?<segment>.*), /api-docs$\{segment}
                - RewritePath=/order-service/swagger-ui(?<segment>.*), /swagger-ui$\{segment}

            - id: product-service-docs
              uri: lb://product-service
              predicates:
                - Path=/product-service/api-docs/**,/product-service/swagger-ui/**
              filters:
                - RewritePath=/product-service/api-docs(?<segment>.*), /api-docs$\{segment}
                - RewritePath=/product-service/swagger-ui(?<segment>.*), /swagger-ui$\{segment}


          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:5173"
                allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
                allowedHeaders: "*"
                allowCredentials: true
                allowed-methods:
                  - POST
                  - GET
                  - OPTIONS
                  - PUT
                  - DELETE
                maxAge: 3600
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Cart Service
        url: /cart-service/api-docs
      - name: Auth Service
        url: /auth-service/api-docs
      - name: Order Service
        url: /order-service/api-docs
      - name: Product Service
        url: /product-service/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

jwt:
  secret:
    key: my_super_secret_key_1234567890_abcdefghij
